#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>

int main(){
  pid_t pid;
  
  printf("Program has started. Till here no fork() has been done so will be printed once only\n");

  pid=fork();

  switch(pid){
    case -1:
      printf("Error");
      exit(1);
    
    case 0:
      printf("This is the child proccess\n");
      printf("Child PID=%d\n", getpid());
      printf("Parent PID (generated by child)= %d\n", getppid());
      break;
    
    default:
      printf("This is the Parent Process\n");
      printf("Parent PID =%d\n", getpid());
      printf("Child PID (generated by the parent) = %d\n", pid);
      break;
  }

  printf("Process Execution completed (It will be printed twice since it is after fork and once printed by the child and once by the parent)\n");

  return 0;
}